Can the performance of the selected model be improved?
Machine learning models contain hyperparameters that control how the model learns from the data. Instead of using the default settings, hyperparameter tuning searches for better parameter combinations that improve prediction performance.

Can Logistic Regression performance be improved using hyperparameter tuning?

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from imblearn.over_sampling import SMOTE

In [2]:
df = pd.read_csv("../../DATA/featured_telco.csv")

df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,...,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Average Charges,CLTV per Month,High Monthly Charge,Loyal Customer
0,0.990658,-0.440327,-0.965608,-0.547115,-1.239504,0.327189,-0.991564,1.408012,1.242875,-1.026988,...,0,0,1,1,0,0,4.006817,4.105072,0,0
1,-1.009430,-0.440327,-0.965608,1.827769,-1.239504,0.327189,-0.991564,-0.917837,-1.028998,-1.026988,...,0,1,0,0,1,0,3.926687,6.004971,1,0
2,-1.009430,-0.440327,-0.965608,1.827769,-0.995040,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,0,1,0,0,1,0,-130.122842,165.510906,1,0
3,-1.009430,-0.440327,1.035617,1.827769,-0.180161,0.327189,1.116896,-0.917837,-1.028998,1.245441,...,0,1,0,0,1,0,0.410465,0.620595,1,0
4,0.990658,-0.440327,-0.965608,1.827769,0.675462,0.327189,1.116896,-0.917837,1.242875,1.245441,...,0,0,0,0,1,0,0.724928,0.473790,1,1


In [3]:
X = df.drop(columns=["Churn Label"])

y = df["Churn Label"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [5]:
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

In [6]:
logistic = LogisticRegression(max_iter=1000)

C → بيتحكم فى قوة الـ Regularization.
solver → طريقة تدريب الموديل.

In [7]:
param_grid = {

    "C":[0.01,0.1,1,10],

    "solver":[
        "liblinear",
        "lbfgs"
    ]

}

In [8]:
grid_search = GridSearchCV(

    estimator=logistic,

    param_grid=param_grid,

    cv=5,

    scoring="accuracy",

    n_jobs=-1

)

In [9]:
grid_search.fit(
    X_train_smote,
    y_train_smote
)

,estimator,LogisticRegre...max_iter=1000)
,param_grid,"{'C': [0.01, 0.1, ...], 'solver': ['liblinear', 'lbfgs']}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [10]:
print("Best Parameters:")

print(grid_search.best_params_)

Best Parameters:
{'C': 10, 'solver': 'lbfgs'}


In [12]:
print("Best CV Score:")

print(grid_search.best_score_)

Best CV Score:
0.8334140435835351


Interpretation


Grid Search identified the optimal hyperparameter combination for Logistic Regression. These parameters are expected to improve model performance compared to the default configuration.

 Interpretation

The optimized Logistic Regression achieved an average cross-validation accuracy of XX%.

What are Hyperparameters?

Hyperparameters are settings that control how a machine learning model is trained. They are selected before training begins.

Examples:

Number of trees
Maximum tree depth
Minimum samples required to split

Which hyperparameters should be optimized?

Parameter	        Meaning


n_estimators	    Number of trees


max_depth	        Maximum depth of each tree


min_samples_split	Minimum samples needed to split a node


min_samples_leaf	Minimum samples in each leaf


Can Random Forest performance be improved using hyperparameter tuning?

In [13]:
from sklearn.ensemble import RandomForestClassifier

Create the model

In [14]:
rf = RandomForestClassifier(
    random_state=42
)

Create parameter grid

In [15]:
param_grid = {

    "n_estimators":[
        100,
        200,
        300
    ],

    "max_depth":[
        10,
        20,
        None
    ],

    "min_samples_split":[
        2,
        5,
        10
    ]

}

How can Grid Search find the best parameters?

Grid Search trains the model using every possible parameter combination and evaluates each one using cross-validation. The combination with the highest validation score is selected as the best model.

In [16]:
grid_search_rf = GridSearchCV(

    estimator=rf,

    param_grid=param_grid,

    cv=5,

    scoring="accuracy",

    n_jobs=-1

)

try it out!!!!!!!

In [17]:
grid_search_rf.fit(
    X_train_smote,
    y_train_smote
)

,estimator,RandomForestC...ndom_state=42)
,param_grid,"{'max_depth': [10, 20, ...], 'min_samples_split': [2, 5, ...], 'n_estimators': [100, 200, ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_estimators,200


What is the best parameter combination?



In [18]:
print("Best Parameters")

print(grid_search_rf.best_params_)

Best Parameters
{'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}


In [ ]:
print("Best Accuracy:")
print(grid_search.best_score_)

Best CV Score
0.8641646489104117


Interpretation

Grid Search successfully identified the optimal Random Forest configuration that achieved the highest cross-validation score

Which tuned model achieved better performance?

In [20]:
comparison = pd.DataFrame({

    "Model":[

        "Logistic Regression",

        "Random Forest"

    ],

    "Best CV Score":[

        grid_search.best_score_,

        grid_search_rf.best_score_

    ]

})

comparison

,Model,Best CV Score
0,Logistic Regression,0.833414
1,Random Forest,0.864165


 Key Insights


Hyperparameter tuning successfully improved the selected machine learning models by identifying their optimal parameter combinations.


Random Forest achieved the highest cross-validation score (86.42%), outperforming Logistic Regression (83.34%).


The results indicate that the tuned Random Forest model has better generalization capability and is the strongest candidate for the final deployment model.


Logistic Regression also demonstrated strong performance but remained slightly below Random Forest after optimization.


Based on these results, Random Forest will be selected for the final model comparison and deployment stage.